"""
Usage-based type stubs
Generated from analysis of actual code usage patterns
"""

from typing import Any, Dict, List, Optional, Union, Sequence

# Commonly used imports
import langchain.agents
import langchain_core.messages
import langchain_core.runnables

# Frequently called functions
def APIRouter(*args, **kwargs) -> Any: ...
def print(*args, **kwargs) -> Any: ...
def load_dotenv(*args, **kwargs) -> Any: ...
def create_agent(*args, **kwargs) -> Any: ...
def run_agent_with_messages(*args, **kwargs) -> Any: ...
def HumanMessage(*args, **kwargs) -> Any: ...
def AIMessage(*args, **kwargs) -> Any: ...
def AnthropicChatDataSchema(*args, **kwargs) -> Any: ...
def test(*args, **kwargs) -> Any: ...
def MessageSchema(*args, **kwargs) -> Any: ...
