"""
Auto-generated type stubs for langchain_core
Generated by runtime inspection
"""

from typing import Any, Dict, List, Optional, Union, Sequence

def surface_langchain_beta_warnings() -> <class 'NoneType'>:
    """Unmute LangChain beta warnings."""
    ...

def surface_langchain_deprecation_warnings() -> <class 'NoneType'>:
    """Unmute LangChain deprecation warnings."""
    ...
